<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 3" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="/Users/oscar/Documents/College/Fundamentals of Programming/Eclipse1/Lab02-04/Lab02-04/main.py" status="error" test="main" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/Applications/Eclipse.app/Contents/Eclipse/plugins/org.python.pydev_5.3.0.201610121612/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/Users/oscar/Documents/College/Fundamentals of Programming/Eclipse1/Lab02-04/Lab02-04/main.py", line 6, in <module>
    from zope.interface._compat import PYTHON3
ImportError: No module named 'zope'
ERROR: Module: main could not be imported (file: /Users/oscar/Documents/College/Fundamentals of Programming/Eclipse1/Lab02-04/Lab02-04/main.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Lab02-04 main.py (1)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
